name: meng-admin-gin
description: 基于gin+React+antd的RBAC权限管理系统
version: 0.0.1

captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600

redis:
  addr: 127.0.0.1:6379
  password:
  db: 0

system:
  env: "prod"
  db-type: "mysql"
  oss-type: "local"
  router-prefix: ""
  port: 8090
  iplimit-count: 15000
  iplimit-time: 3600
  cache-type: "redis" # 缓存类型 redis 或 memory
  use-multipoint: false
  use-redis: false # 是否启用redis缓存
  use-mongo: false

jwt:
  signing-key: zjRW6R^MpK!Z&&&H^3gV%Kya&uTMBW!j
  expires-time: 7d  # 7天过期
  buffer-time: 1d   # 1天缓冲期，距离过期还有1天会生成新的token
  issuer: "meng-admin"
local:
  path: uploads/file
  store-path: uploads/file

zap:
  level: error
  prefix: '[Meng Admin]'
  format: json
  director: log
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  max-age: 30  # 日志保留30天
  show-line: true
  log-in-console: false

mysql:
  prefix: ""
  port: "33306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: meng-admin
  username: root
  password: 955330@_
  path: 127.0.0.1
  engine: ""
  log-mode: error
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false