definitions:
  dto.LoginResp:
    properties:
      expiresAt:
        type: integer
      token:
        type: string
      user:
        $ref: '#/definitions/system.SysUser'
    type: object
  request.Login:
    properties:
      captcha:
        description: 验证码
        type: string
      captchaId:
        description: 验证码ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      msg: {}
      requestId:
        description: 数据集
        type: string
      status:
        type: string
    type: object
  system.SysDept:
    properties:
      children:
        items:
          $ref: '#/definitions/system.SysDept'
        type: array
      createBy:
        type: integer
      createdAt:
        type: string
      dataScope:
        type: string
      deptId:
        description: 部门编码
        type: integer
      deptName:
        description: 部门名称
        type: string
      deptPath:
        type: string
      email:
        description: 邮箱
        type: string
      leader:
        description: 负责人
        type: string
      params:
        type: string
      parentId:
        description: 上级部门
        type: integer
      phone:
        description: 手机
        type: string
      sort:
        description: 排序
        type: integer
      status:
        description: 状态
        type: integer
      updateBy:
        type: integer
      updatedAt:
        type: string
    type: object
  system.SysUser:
    properties:
      avatar:
        description: 用户头像
        type: string
      createBy:
        type: integer
      createdAt:
        type: string
      dept:
        $ref: '#/definitions/system.SysDept'
      deptId:
        type: integer
      deptIds:
        items:
          type: integer
        type: array
      email:
        description: 用户邮箱
        type: string
      nickName:
        description: 用户昵称
        type: string
      phone:
        description: 用户手机号
        type: string
      postId:
        type: integer
      postIds:
        items:
          type: integer
        type: array
      remark:
        description: 用户是否被冻结 1正常 2冻结
        type: string
      roleId:
        type: integer
      roleIds:
        items:
          type: integer
        type: array
      sex:
        description: 性别
        type: string
      status:
        type: integer
      updateBy:
        type: integer
      updatedAt:
        type: string
      userId:
        description: gorm.Model
        type: integer
      userName:
        description: 用户登录名
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/login:
    post:
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: 返回包括用户信息,token,过期时间
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginResp'
                msg:
                  type: string
              type: object
      summary: 用户登录
      tags:
      - Base
swagger: "2.0"
